FROM node:18 as build

WORKDIR /app
COPY . .

ARG VITE_AWS_KEY
ARG VITE_AWS_SECRET
ARG VITE_AUTH_URL
ARG VITE_PROJECT_ID
ARG VITE_CARGO_ENDPOINT
ARG VITE_S3_ENDPOINT
ARG VITE_AUTHSERVICE_URL

ENV VITE_AWS_KEY ${VITE_AWS_KEY}
ENV VITE_AWS_SECRET ${VITE_AWS_SECRET}
ENV VITE_AUTH_URL ${VITE_AUTH_URL}
ENV VITE_PROJECT_ID ${VITE_PROJECT_ID}
ENV VITE_CARGO_ENDPOINT ${VITE_CARGO_ENDPOINT}
ENV VITE_S3_ENDPOINT ${VITE_S3_ENDPOINT}
ENV VITE_AUTHSERVICE_URL ${VITE_AUTHSERVICE_URL}

RUN npm install
RUN npm run build

FROM registry.access.redhat.com/ubi7/nginx-120

COPY --from=builder /app/dist .

ADD ./nginx.conf "${NGINX_CONF_PATH}"

CMD nginx -g "daemon off;"
